### ISSUE TITLE
Error on rendering: Notice: Undefined variable: trackerPath

### ISSUE THREAD

**Issue by bretrzaun** [shapecode/matomo-bundle#1]
When using the bundle as documented I get the following error:

> An exception has been thrown during the rendering of a template ("Notice: Undefined variable: trackerPath").

Looking at the source code (MatomoExtension.php - getResolver()) this is obvious since the variable $trackerPath is actually not defined. It listed as constructor parameter but used nowhere.

**Comment by nicklog** [comment]
I'll check it out later today and fix it :)

**Comment by nicklog** [comment]
done.
